package com.eli.oneos.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BACKUP_FILE.
 */
public class BackupFile {

    private Long id;
    private long uid;
    /** Not-null value. */
    private String path;
    private Boolean auto;
    private Integer type;
    private Integer priority;
    private Long time;
    private Long count;

    public BackupFile() {
    }

    public BackupFile(Long id) {
        this.id = id;
    }

    public BackupFile(Long id, long uid, String path, Boolean auto, Integer type, Integer priority, Long time, Long count) {
        this.id = id;
        this.uid = uid;
        this.path = path;
        this.auto = auto;
        this.type = type;
        this.priority = priority;
        this.time = time;
        this.count = count;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getUid() {
        return uid;
    }

    public void setUid(long uid) {
        this.uid = uid;
    }

    /** Not-null value. */
    public String getPath() {
        return path;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPath(String path) {
        this.path = path;
    }

    public Boolean getAuto() {
        return auto;
    }

    public void setAuto(Boolean auto) {
        this.auto = auto;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getPriority() {
        return priority;
    }

    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Long getCount() {
        return count;
    }

    public void setCount(Long count) {
        this.count = count;
    }

}
