package com.eli.oneos.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BACKUP_INFO.
 */
public class BackupInfo {

    private Long id;
    private Long uid;
    private Integer type;
    private Long count;
    private Long time;

    public BackupInfo() {
    }

    public BackupInfo(Long id) {
        this.id = id;
    }

    public BackupInfo(Long id, Long uid, Integer type, Long count, Long time) {
        this.id = id;
        this.uid = uid;
        this.type = type;
        this.count = count;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUid() {
        return uid;
    }

    public void setUid(Long uid) {
        this.uid = uid;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Long getCount() {
        return count;
    }

    public void setCount(Long count) {
        this.count = count;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

}
