package com.eli.oneos.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table DEVICE_INFO.
 */
public class DeviceInfo {

    /**
     * Not-null value.
     */
    private String mac;
    private String name;
    private String lanIp;
    private String lanPort;
    private String wanIp;
    private String wanPort;
    private String ssudpCid;
    private String ssudpPwd;
    private Integer domain;
    private Long time;

    public DeviceInfo() {
    }

    public DeviceInfo(String mac) {
        if (mac != null) {
            mac = mac.toUpperCase();
        }
        this.mac = mac;
    }

    public DeviceInfo(String mac, String name, String lanIp, String lanPort, String wanIp, String wanPort, String ssudpCid, String ssudpPwd, Integer domain, Long time) {
        this.mac = mac;
        this.name = name;
        this.lanIp = lanIp;
        this.lanPort = lanPort;
        this.wanIp = wanIp;
        this.wanPort = wanPort;
        this.ssudpCid = ssudpCid;
        this.ssudpPwd = ssudpPwd;
        this.domain = domain;
        this.time = time;
    }

    /**
     * Not-null value.
     */
    public String getMac() {
        return mac;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setMac(String mac) {
        if (mac != null) {
            mac = mac.toUpperCase();
        }
        this.mac = mac;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLanIp() {
        return lanIp;
    }

    public void setLanIp(String lanIp) {
        this.lanIp = lanIp;
    }

    public String getLanPort() {
        return lanPort;
    }

    public void setLanPort(String lanPort) {
        this.lanPort = lanPort;
    }

    public String getWanIp() {
        return wanIp;
    }

    public void setWanIp(String wanIp) {
        this.wanIp = wanIp;
    }

    public String getWanPort() {
        return wanPort;
    }

    public void setWanPort(String wanPort) {
        this.wanPort = wanPort;
    }

    public String getSsudpCid() {
        return ssudpCid;
    }

    public void setSsudpCid(String ssudpCid) {
        this.ssudpCid = ssudpCid;
    }

    public String getSsudpPwd() {
        return ssudpPwd;
    }

    public void setSsudpPwd(String ssudpPwd) {
        this.ssudpPwd = ssudpPwd;
    }

    public Integer getDomain() {
        return domain;
    }

    public void setDomain(Integer domain) {
        this.domain = domain;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

}
