package com.eli.oneos.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TRANSFER_HISTORY.
 */
public class TransferHistory {

    private Long id;
    private Long uid;
    private Integer type;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String srcPath;
    /** Not-null value. */
    private String toPath;
    private Long size;
    private Long length;
    private Long duration;
    private Long time;
    private Boolean isComplete;

    public TransferHistory() {
    }

    public TransferHistory(Long id) {
        this.id = id;
    }

    public TransferHistory(Long id, Long uid, Integer type, String name, String srcPath, String toPath, Long size, Long length, Long duration, Long time, Boolean isComplete) {
        this.id = id;
        this.uid = uid;
        this.type = type;
        this.name = name;
        this.srcPath = srcPath;
        this.toPath = toPath;
        this.size = size;
        this.length = length;
        this.duration = duration;
        this.time = time;
        this.isComplete = isComplete;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUid() {
        return uid;
    }

    public void setUid(Long uid) {
        this.uid = uid;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getSrcPath() {
        return srcPath;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSrcPath(String srcPath) {
        this.srcPath = srcPath;
    }

    /** Not-null value. */
    public String getToPath() {
        return toPath;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setToPath(String toPath) {
        this.toPath = toPath;
    }

    public Long getSize() {
        return size;
    }

    public void setSize(Long size) {
        this.size = size;
    }

    public Long getLength() {
        return length;
    }

    public void setLength(Long length) {
        this.length = length;
    }

    public Long getDuration() {
        return duration;
    }

    public void setDuration(Long duration) {
        this.duration = duration;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Boolean getIsComplete() {
        return isComplete;
    }

    public void setIsComplete(Boolean isComplete) {
        this.isComplete = isComplete;
    }

}
