package com.eli.oneos.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_SETTINGS.
 */
public class UserSettings {

    private long uid;
    private String downloadPath;
    private Boolean isAutoBackupFile;
    private Boolean isAutoBackupAlbum;
    private Boolean isPreviewPicOnlyWifi;
    private Boolean isTipTransferNotWifi;
    private Boolean isBackupFileOnlyWifi;
    private Boolean isBackupAlbumOnlyWifi;
    private Integer fileOrderType;
    private Integer fileViewerType;
    private Long time;

    public UserSettings() {
    }

    public UserSettings(long uid) {
        this.uid = uid;
    }

    public UserSettings(long uid, String downloadPath, Boolean isAutoBackupFile, Boolean isAutoBackupAlbum, Boolean isPreviewPicOnlyWifi, Boolean isTipTransferNotWifi, Boolean isBackupFileOnlyWifi, Boolean isBackupAlbumOnlyWifi, Integer fileOrderType, Integer fileViewerType, Long time) {
        this.uid = uid;
        this.downloadPath = downloadPath;
        this.isAutoBackupFile = isAutoBackupFile;
        this.isAutoBackupAlbum = isAutoBackupAlbum;
        this.isPreviewPicOnlyWifi = isPreviewPicOnlyWifi;
        this.isTipTransferNotWifi = isTipTransferNotWifi;
        this.isBackupFileOnlyWifi = isBackupFileOnlyWifi;
        this.isBackupAlbumOnlyWifi = isBackupAlbumOnlyWifi;
        this.fileOrderType = fileOrderType;
        this.fileViewerType = fileViewerType;
        this.time = time;
    }

    public long getUid() {
        return uid;
    }

    public void setUid(long uid) {
        this.uid = uid;
    }

    public String getDownloadPath() {
        return downloadPath;
    }

    public void setDownloadPath(String downloadPath) {
        this.downloadPath = downloadPath;
    }

    public Boolean getIsAutoBackupFile() {
        return isAutoBackupFile;
    }

    public void setIsAutoBackupFile(Boolean isAutoBackupFile) {
        this.isAutoBackupFile = isAutoBackupFile;
    }

    public Boolean getIsAutoBackupAlbum() {
        return isAutoBackupAlbum;
    }

    public void setIsAutoBackupAlbum(Boolean isAutoBackupAlbum) {
        this.isAutoBackupAlbum = isAutoBackupAlbum;
    }

    public Boolean getIsPreviewPicOnlyWifi() {
        return isPreviewPicOnlyWifi;
    }

    public void setIsPreviewPicOnlyWifi(Boolean isPreviewPicOnlyWifi) {
        this.isPreviewPicOnlyWifi = isPreviewPicOnlyWifi;
    }

    public Boolean getIsTipTransferNotWifi() {
        return isTipTransferNotWifi;
    }

    public void setIsTipTransferNotWifi(Boolean isTipTransferNotWifi) {
        this.isTipTransferNotWifi = isTipTransferNotWifi;
    }

    public Boolean getIsBackupFileOnlyWifi() {
        return isBackupFileOnlyWifi;
    }

    public void setIsBackupFileOnlyWifi(Boolean isBackupFileOnlyWifi) {
        this.isBackupFileOnlyWifi = isBackupFileOnlyWifi;
    }

    public Boolean getIsBackupAlbumOnlyWifi() {
        return isBackupAlbumOnlyWifi;
    }

    public void setIsBackupAlbumOnlyWifi(Boolean isBackupAlbumOnlyWifi) {
        this.isBackupAlbumOnlyWifi = isBackupAlbumOnlyWifi;
    }

    public Integer getFileOrderType() {
        return fileOrderType;
    }

    public void setFileOrderType(Integer fileOrderType) {
        this.fileOrderType = fileOrderType;
    }

    public Integer getFileViewerType() {
        return fileViewerType;
    }

    public void setFileViewerType(Integer fileViewerType) {
        this.fileViewerType = fileViewerType;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

}
